services:
  stack:
    container_name: stackc
    build: .
    command: "cd ~/DeepHoldem/ACPCServer && ./dealer matchName holdem.limit.2p.reverse_blinds.game 1000 0 Alice Bob 16177 48777"
    ports:
      - "16177:16177"
      - "48777:48777"
    networks:
      - stack
    volumes:
      - ~/logs-stack:/home/logs
    hostname: stackapi



  caddy:
    container_name: caddyc
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - stack



networks:
  stack:
    external: true
